---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    # You must replace this email address with your own.
    # Let’s Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: jim@jimpick.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-prod-acc-key
    solvers:
      - dns01:
          route53:
            region: us-west-2
            accessKeyIDSecretRef:
              name: prod-route53-credentials-secret
              key: access-key-id
            secretAccessKeySecretRef: 
              name: prod-route53-credentials-secret
              key: secret-access-key
