apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quick-ebs-demo
  namespace: quick  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: quick-ebs-demo
  namespace: quick
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
  resources:
    requests:
      memory: "20Mi"
      cpu: "100m"
    limits:
      memory: "20Mi"
      cpu: "100m"

