apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: glif-fvm-v1-20-0-20230213-0d92c74-test
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "60m"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      volumes:
        - name: coordination
          emptyDir: {}
      containers:
      - name: node
        image: ghcr.io/jimpick/lotus-fvm-localnet-python@sha256:3d2763ee715a3a86e17ba346984030462d5fc6092309117fbd0b557c02435df1
        command: [ bash, -c ]
        args:
          - |
            #while true; do sleep 50; done
            (cd ~/.lotus-local-net; python3 -m http.server 11001) &
            lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "400m"
            ephemeral-storage: "2Gi"
        volumeMounts:
          - name: coordination
            mountPath: /coordination
      - name: gateway
        image: ghcr.io/jimpick/localnet-farm-gateway@sha256:a59e27b2aa1ab8c8deb4b448061fedc669eaf75e78e7fd1471931414f8c4e13b
        command: [ bash, -c ]
        args:
          - |
            caddy start --config /etc/caddy/Caddyfile
            echo 1 > /coordination/generation
            node server.mjs
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: coordination
            mountPath: /coordination
        livenessProbe:
          exec:
            command:
            - cat
            - /coordination/generation
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 1
      - name: miner-1
        image: ghcr.io/jimpick/lotus-fvm-localnet-python@sha256:3d2763ee715a3a86e17ba346984030462d5fc6092309117fbd0b557c02435df1
        command: [ bash, -c ]
        args:
          - |
            #while true; do sleep 50; done
            lotus-miner run --nosync
        env:
          - name: LOTUS_DEALMAKING_PUBLISHMSGPERIOD
            value: "0h0m30s"
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "400m"
            ephemeral-storage: "2Gi"
        volumeMounts:
          - name: coordination
            mountPath: /coordination
        livenessProbe:
          exec:
            command:
            - cat
            - /coordination/generation
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 1
      - name: miner-2
        image: ghcr.io/jimpick/lotus-fvm-localnet-python@sha256:3d2763ee715a3a86e17ba346984030462d5fc6092309117fbd0b557c02435df1
        command: [ bash, -c ]
        args:
          - |
            lotus wait-api
            mkdir ~/.lotus-miner-local-net-2
            export OWNER=$(lotus wallet default)
            echo Owner: $OWNER
            echo LOTUS_MINER_PATH: $LOTUS_MINER_PATH
            #while true; do sleep 50; done
            lotus-miner init --owner $OWNER --nosync --sector-size 2048
            lotus-miner run --nosync --miner-api 2346
        env:
          - name: LOTUS_MINER_PATH
            value: ~/.lotus-miner-local-net-2
          - name: LOTUS_DEALMAKING_PUBLISHMSGPERIOD
            value: "0h0m30s"
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            cpu: "400m"
            ephemeral-storage: "2Gi"
