apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-rootcache
spec:
  commonName: hello.rootcache.com
  secretName: hello-rootcache-cert
  dnsNames:
    - hello.rootcache.com
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-v6z
spec:
  commonName: hello.v6z.me
  secretName: hello-v6z-cert
  dnsNames:
    - hello.v6z.me
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
