apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: hello.rootcache.com
  namespace: default
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hello-rootcache
    namespace: default
	tls:
    secretName: hello-rootcache-cert
