apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-rootcache
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
