apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-rootcache
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
