apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serving-core-customized.yaml
- github.com/knative/net-contour/releases/download/knative-v1.12.1/contour.yaml
- github.com/knative/net-contour/releases/download/knative-v1.12.1/net-contour.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: envoy
      namespace: contour-external
    spec:
      externalIPs:
        - 52.12.167.0
      ports:
        - name: http
          nodePort: 30080
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          nodePort: 30443
          port: 443
          protocol: TCP
          targetPort: 8443
      type: NodePort
