apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-webrtc-star-dev
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      containers:
      - name: webrtc-star
        image: ghcr.io/hexcamp/hexcamp-webrtc-star@sha256:8efe4f06aa34a82eec6d425954b737b1e4869cf7008a00961d07b1dca98794a6
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
