apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-libp2p-webrtc-relay
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      containers:
      - name: webrtc-relay
        image: ghcr.io/hexcamp/hexcamp-libp2p-webrtc-relay@sha256:6db9294a45b8023bdb93633c9f9939a49aa1a727a2d55db322437a973aacde9b
        env:
          - name: ANNOUNCE
            value: /dns4/hexcamp-libp2p-webrtc-relay.quick.cluster-4.localnet.farm/tcp/443/wss
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
