apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hexcamp-webrtc-star-dev
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      containers:
      - name: webrtc-star
        image: ghcr.io/hexcamp/hexcamp-webrtc-star@sha256:465ff27133bac988c688dce03119d287a6c28db062ff3bc878bb3de103aeab9c
        ports:
          - containerPort: 9090
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
