apiVersion: v1
kind: Namespace
metadata:
  name: quick
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m"
    spec:
      containerConcurrency: 0
      containers:
      - name: hello
        image: gcr.io/knative-samples/helloworld-go
        ports:
          - containerPort: 8080
