apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quick-efs-demo
  namespace: quick
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "15m"
    spec:
      containerConcurrency: 0
      timeoutSeconds: 120
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          volumeMounts:
          - name: persistent-storage
            mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: quick-efs-claim
