apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blocksonachain-fvm-sapphire-patch-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "3m"
    spec:
      containerConcurrency: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: gateway
        image: ghcr.io/jimpick/localnet-farm-gateway@sha256:a59e27b2aa1ab8c8deb4b448061fedc669eaf75e78e7fd1471931414f8c4e13b
        command: [ bash, -c ]
        args:
          - |
            caddy start --config /etc/caddy/Caddyfile
            node server.mjs
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      - name: node
        image: ghcr.io/jimpick/lotus-fvm-localnet-python@sha256:9d6ecc137bcc513e2a8af3161dcd3ef506b705b4bb9ff6f9cdff98337a459612
        command: [ bash, -c ]
        args:
          - |
            #while true; do sleep 50; done
            (cd ~/.lotus-local-net; python3 -m http.server 11001) &
            lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "200m"
      - name: miner-1
        image: ghcr.io/jimpick/lotus-fvm-localnet-python@sha256:9d6ecc137bcc513e2a8af3161dcd3ef506b705b4bb9ff6f9cdff98337a459612
        command: [ bash, -c ]
        args:
          - |
            #while true; do sleep 50; done
            lotus-miner run --nosync
        env:
          - name: LOTUS_DEALMAKING_PUBLISHMSGPERIOD
            value: "0h0m30s"
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "200m"
