---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coredns-test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/centos/storage/coredns-test"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coredns-test
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: coredns-test
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: app
    image: ghcr.io/hexcamp/hexcamp-coredns-with-dnsredir-image@sha256:5bb1a2926c4bb183e8e02d6094da943c791d998439f4555a25a754af40615fe5
    command: ["/coredns"]
    args: ["-conf", "/data/Corefile"]
    #args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
    ports:
    - hostPort: 53
      containerPort: 53
      protocol: "UDP"
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: coredns-test
