---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-storage-demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/storage/manual-storage-demo"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manual-storage-demo
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: manual-storage-demo
  namespace: default
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
    resources:
      requests:
        memory: "20Mi"
        cpu: "100m"
      limits:
        memory: "20Mi"
        cpu: "100m"
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: manual-storage-demo
